apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::208783422476:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WZ1I8I9WKVWE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::208783422476:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-16T11:23:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1593"
  uid: c79bb8c4-45a3-4a8f-854c-e966586cceea
